/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as TestSceneCreationRouteImport } from './routes/test-scene-creation'
import { Route as TestManualSaveRouteImport } from './routes/test-manual-save'
import { Route as TestFocusRouteImport } from './routes/test-focus'
import { Route as TestClearDataRouteImport } from './routes/test-clear-data'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutlineRouteImport } from './routes/outline'
import { Route as LogRouteImport } from './routes/log'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTypographyRouteImport } from './routes/settings/typography'
import { Route as SettingsScrollTestRouteImport } from './routes/settings/scroll-test'
import { Route as SettingsIconsRouteImport } from './routes/settings/icons'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsEditorRouteImport } from './routes/settings/editor'
import { Route as SettingsDiagramsRouteImport } from './routes/settings/diagrams'
import { Route as SettingsDesignRouteImport } from './routes/settings/design'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSceneCreationRoute = TestSceneCreationRouteImport.update({
  id: '/test-scene-creation',
  path: '/test-scene-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const TestManualSaveRoute = TestManualSaveRouteImport.update({
  id: '/test-manual-save',
  path: '/test-manual-save',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFocusRoute = TestFocusRouteImport.update({
  id: '/test-focus',
  path: '/test-focus',
  getParentRoute: () => rootRouteImport,
} as any)
const TestClearDataRoute = TestClearDataRouteImport.update({
  id: '/test-clear-data',
  path: '/test-clear-data',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlineRoute = OutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTypographyRoute = SettingsTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScrollTestRoute = SettingsScrollTestRouteImport.update({
  id: '/scroll-test',
  path: '/scroll-test',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIconsRoute = SettingsIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEditorRoute = SettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagramsRoute = SettingsDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDesignRoute = SettingsDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/characters': typeof CharactersRoute
  '/log': typeof LogRoute
  '/outline': typeof OutlineRoute
  '/settings': typeof SettingsRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/test-clear-data': typeof TestClearDataRoute
  '/test-focus': typeof TestFocusRoute
  '/test-manual-save': typeof TestManualSaveRoute
  '/test-scene-creation': typeof TestSceneCreationRoute
  '/world': typeof WorldRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/diagrams': typeof SettingsDiagramsRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/icons': typeof SettingsIconsRoute
  '/settings/scroll-test': typeof SettingsScrollTestRoute
  '/settings/typography': typeof SettingsTypographyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/characters': typeof CharactersRoute
  '/log': typeof LogRoute
  '/outline': typeof OutlineRoute
  '/statistics': typeof StatisticsRoute
  '/test-clear-data': typeof TestClearDataRoute
  '/test-focus': typeof TestFocusRoute
  '/test-manual-save': typeof TestManualSaveRoute
  '/test-scene-creation': typeof TestSceneCreationRoute
  '/world': typeof WorldRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/diagrams': typeof SettingsDiagramsRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/icons': typeof SettingsIconsRoute
  '/settings/scroll-test': typeof SettingsScrollTestRoute
  '/settings/typography': typeof SettingsTypographyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/characters': typeof CharactersRoute
  '/log': typeof LogRoute
  '/outline': typeof OutlineRoute
  '/settings': typeof SettingsRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/test-clear-data': typeof TestClearDataRoute
  '/test-focus': typeof TestFocusRoute
  '/test-manual-save': typeof TestManualSaveRoute
  '/test-scene-creation': typeof TestSceneCreationRoute
  '/world': typeof WorldRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/diagrams': typeof SettingsDiagramsRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/icons': typeof SettingsIconsRoute
  '/settings/scroll-test': typeof SettingsScrollTestRoute
  '/settings/typography': typeof SettingsTypographyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/characters'
    | '/log'
    | '/outline'
    | '/settings'
    | '/statistics'
    | '/test-clear-data'
    | '/test-focus'
    | '/test-manual-save'
    | '/test-scene-creation'
    | '/world'
    | '/projects/$projectId'
    | '/settings/about'
    | '/settings/data'
    | '/settings/design'
    | '/settings/diagrams'
    | '/settings/editor'
    | '/settings/export'
    | '/settings/general'
    | '/settings/icons'
    | '/settings/scroll-test'
    | '/settings/typography'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/characters'
    | '/log'
    | '/outline'
    | '/statistics'
    | '/test-clear-data'
    | '/test-focus'
    | '/test-manual-save'
    | '/test-scene-creation'
    | '/world'
    | '/projects/$projectId'
    | '/settings/about'
    | '/settings/data'
    | '/settings/design'
    | '/settings/diagrams'
    | '/settings/editor'
    | '/settings/export'
    | '/settings/general'
    | '/settings/icons'
    | '/settings/scroll-test'
    | '/settings/typography'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/characters'
    | '/log'
    | '/outline'
    | '/settings'
    | '/statistics'
    | '/test-clear-data'
    | '/test-focus'
    | '/test-manual-save'
    | '/test-scene-creation'
    | '/world'
    | '/projects/$projectId'
    | '/settings/about'
    | '/settings/data'
    | '/settings/design'
    | '/settings/diagrams'
    | '/settings/editor'
    | '/settings/export'
    | '/settings/general'
    | '/settings/icons'
    | '/settings/scroll-test'
    | '/settings/typography'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  CharactersRoute: typeof CharactersRoute
  LogRoute: typeof LogRoute
  OutlineRoute: typeof OutlineRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
  TestClearDataRoute: typeof TestClearDataRoute
  TestFocusRoute: typeof TestFocusRoute
  TestManualSaveRoute: typeof TestManualSaveRoute
  TestSceneCreationRoute: typeof TestSceneCreationRoute
  WorldRoute: typeof WorldRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-scene-creation': {
      id: '/test-scene-creation'
      path: '/test-scene-creation'
      fullPath: '/test-scene-creation'
      preLoaderRoute: typeof TestSceneCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-manual-save': {
      id: '/test-manual-save'
      path: '/test-manual-save'
      fullPath: '/test-manual-save'
      preLoaderRoute: typeof TestManualSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-focus': {
      id: '/test-focus'
      path: '/test-focus'
      fullPath: '/test-focus'
      preLoaderRoute: typeof TestFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-clear-data': {
      id: '/test-clear-data'
      path: '/test-clear-data'
      fullPath: '/test-clear-data'
      preLoaderRoute: typeof TestClearDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outline': {
      id: '/outline'
      path: '/outline'
      fullPath: '/outline'
      preLoaderRoute: typeof OutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/typography': {
      id: '/settings/typography'
      path: '/typography'
      fullPath: '/settings/typography'
      preLoaderRoute: typeof SettingsTypographyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scroll-test': {
      id: '/settings/scroll-test'
      path: '/scroll-test'
      fullPath: '/settings/scroll-test'
      preLoaderRoute: typeof SettingsScrollTestRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/icons': {
      id: '/settings/icons'
      path: '/icons'
      fullPath: '/settings/icons'
      preLoaderRoute: typeof SettingsIconsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/editor': {
      id: '/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof SettingsEditorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagrams': {
      id: '/settings/diagrams'
      path: '/diagrams'
      fullPath: '/settings/diagrams'
      preLoaderRoute: typeof SettingsDiagramsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/design': {
      id: '/settings/design'
      path: '/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof SettingsDesignRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDesignRoute: typeof SettingsDesignRoute
  SettingsDiagramsRoute: typeof SettingsDiagramsRoute
  SettingsEditorRoute: typeof SettingsEditorRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIconsRoute: typeof SettingsIconsRoute
  SettingsScrollTestRoute: typeof SettingsScrollTestRoute
  SettingsTypographyRoute: typeof SettingsTypographyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDesignRoute: SettingsDesignRoute,
  SettingsDiagramsRoute: SettingsDiagramsRoute,
  SettingsEditorRoute: SettingsEditorRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIconsRoute: SettingsIconsRoute,
  SettingsScrollTestRoute: SettingsScrollTestRoute,
  SettingsTypographyRoute: SettingsTypographyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  CharactersRoute: CharactersRoute,
  LogRoute: LogRoute,
  OutlineRoute: OutlineRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
  TestClearDataRoute: TestClearDataRoute,
  TestFocusRoute: TestFocusRoute,
  TestManualSaveRoute: TestManualSaveRoute,
  TestSceneCreationRoute: TestSceneCreationRoute,
  WorldRoute: WorldRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
