name: grain-editor
base: core22
version: '0.1.90'
summary: Modern writing tool for long-form content and knowledge management
description: |
  Grain (小麦) is a professional writing application designed for long-form 
  writing, knowledge management, and creative expression. Built with modern 
  web technologies and powered by the Lexical rich-text editor, it provides 
  everything you need to organize your thoughts and craft compelling content.

  🚀 KEY FEATURES:
  
  ✍️ Immersive Writing Experience
  • Rich-text editing with Markdown shortcuts
  • Distraction-free writing environment
  • Real-time auto-save to prevent data loss
  • Multiple export formats (Markdown, DOCX, JSON)
  
  📂 Flexible Organization
  • Tree-based file management system
  • Multiple workspace support
  • Drag-and-drop file organization
  • Global search across all content
  
  🏷️ Tag System
  • Organize content with #[tags]
  • Quick tag creation and management
  • Tag-based filtering and search
  • Visual tag relationships
  
  👤 Wiki Links & References
  • Quick references via @ symbol
  • Hover preview for linked content
  • Bidirectional linking
  • Knowledge graph visualization
  
  📝 Daily Journal
  • Built-in diary system
  • Daily writing templates
  • Calendar view for entries
  • Writing streak tracking
  
  📊 Outline & Visualization
  • Mermaid diagram support
  • PlantUML integration
  • Visual outline management
  • Chart and graph creation
  
  🎨 Customizable Interface
  • Multiple editor themes
  • Icon theme customization (6 presets)
  • Dark/light mode support
  • Responsive design
  
  🔒 Privacy-First Design
  • Complete local data storage (IndexedDB)
  • No cloud dependency
  • Offline-first architecture
  • Your data stays on your device
  
  Perfect for writers, researchers, students, and anyone who needs a powerful 
  tool for organizing thoughts and creating long-form content. Whether you're 
  writing novels, research papers, documentation, or personal journals, Grain 
  provides the tools to bring your ideas to life.

  ---
  
  Note: This application was formerly known as "Novel Editor". We've rebranded 
  to "Grain" to better reflect our expanded focus on general writing and 
  knowledge management.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  grain:
    command: bin/grain
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - removable-media

parts:
  grain:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - file
      - unzip
      - libwebkit2gtk-4.1-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - patchelf
      - build-essential
      - pkg-config
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgtk-3-0
      - libayatana-appindicator3-1
      - librsvg2-2
    override-build: |
      set -eux
      
      echo "=== Installing Bun ==="
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun --version
      
      echo "=== Installing Rust ==="
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      export PATH="$HOME/.cargo/bin:$PATH"
      rustc --version
      cargo --version
      
      echo "=== Installing root dependencies ==="
      cd $CRAFT_PART_SRC
      bun install
      
      echo "=== Installing desktop dependencies ==="
      cd apps/desktop
      bun install
      
      echo "=== Building desktop frontend ==="
      bun run build
      
      # Verify build output
      if [ ! -d "dist" ]; then
        echo "ERROR: Frontend build failed - dist directory not found"
        exit 1
      fi
      
      echo "=== Building Tauri application ==="
      bun run tauri build --bundles deb
      
      echo "=== Extracting deb package ==="
      DEB_FILE=$(find src-tauri/target/release/bundle/deb -name "*.deb" | head -n 1)
      if [ -z "$DEB_FILE" ]; then
        echo "ERROR: No deb file found"
        exit 1
      fi
      
      echo "Found deb: $DEB_FILE"
      dpkg-deb -x $DEB_FILE $CRAFT_PART_INSTALL
      
      echo "=== Setting up binary ==="
      mkdir -p $CRAFT_PART_INSTALL/bin
      
      # Find and copy binary
      BINARY_PATH=$(find $CRAFT_PART_INSTALL -type f -name "grain" -executable | head -n 1)
      if [ -n "$BINARY_PATH" ]; then
        echo "Found binary at: $BINARY_PATH"
        cp "$BINARY_PATH" $CRAFT_PART_INSTALL/bin/grain
        chmod +x $CRAFT_PART_INSTALL/bin/grain
      else
        echo "ERROR: Binary not found, listing all files:"
        find $CRAFT_PART_INSTALL -type f
        exit 1
      fi
      
      echo "=== Verifying binary ==="
      ls -la $CRAFT_PART_INSTALL/bin/
      
      echo "=== Build completed successfully ==="
